name: Linux.

on: [push]
jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone.
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - uses: GuillaumeFalourd/setup-rsync@v1.1

      - name: First set up.
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install ninja-build
          sudo apt-get install -yq g++-multilib libfreetype6-dev libgl1-mesa-dev libx11-dev libxcursor-dev libxext-dev pkg-config wine-stable wine64-tools
          sudo apt-get install -yq binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 mingw-w64

      - name: Build.
        run: |
          # bash ./clean.sh
          wget --no-check-certificate https://download.qemu.org/qemu-7.2.0.tar.xz
          tar xf qemu-7.2.0.tar.xz
          rm -rfv qemu-7.2.0.tar.xz
          cd qemu-7.2.0
          rsync -r ../qemu-0/hw/3dfx ./hw/
          rsync -r ../qemu-1/hw/mesa ./hw/
          patch -p0 -i ../00-qemu720-mesa-glide.patch
          bash ../scripts/sign_commit
          rm -rfv ../build && mkdir ../build && cd ../build
          ../qemu-7.2.0/configure --target-list=i386-softmmu --cross-prefix=w64-mingw32- && make -j
          # bash ./after-build-cleanup.sh
