name: Linux.

on: [push]
jobs:

  linux:
    runs-on: windows-latest
    steps:
      - name: Clone.
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - uses: GuillaumeFalourd/setup-rsync@v1.1

      - name: First set up.
        run: |
          iwr -OutFile qemu-7.2.0.tar.xz https://download.qemu.org/qemu-7.2.0.tar.xz
          7z x qemu-7.2.0.tar.xz
          7z x qemu-7.2.0.tar
          choco install ninja

      - name: Build.
        shell: bash
        run: |
          # bash ./clean.sh
          rm -rfv qemu-7.2.0.tar.xz
          cd qemu-7.2.0
          rsync -r ../qemu-0/hw/3dfx ./hw/
          rsync -r ../qemu-1/hw/mesa ./hw/
          patch -p0 -i ../00-qemu720-mesa-glide.patch
          bash ../scripts/sign_commit
          rm -rfv ../build && mkdir ../build && cd ../build
          ../qemu-7.2.0/configure --target-list=i386-softmmu --cross-prefix=i686-w64-mingw32- && make -j
          # bash ./after-build-cleanup.sh
